[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Content-Type" = "text/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Content-Type" = "text/css"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    "Content-Type" = "image/x-icon"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
